version: '3'
services:
  nginx:
    container_name: nginx
    depends_on:
        - phpfpm
    image: nginx:1.15-alpine
    restart: unless-stopped
    volumes:
      - ./htdocs:/website
      - ./nginx/development:/etc/nginx/conf.d
    ports:
      - "80:80"
    command: "/bin/sh -c 'while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g \"daemon off;\"'"
  phpfpm:
    container_name: phpfpm
    image: php:7-fpm
    restart: unless-stopped
    volumes:
        - ./htdocs:/website
